Problem-1 (Greedy Search)

In [ ]:
import numpy as np

# Construct the graph and define the heuristics for all nodes
V = [('S', 7), ('A', 9), ('B', 4), ('C',2), ('D', 5), ('E', 3), ('G', 0)] # Set of nodes

E = [('S', 'A'), ('S', 'D'), ('A', 'B'), ('A', 'C'), ('B', 'C'), ('B', 'E'), ('C', 'G'), ('D', 'B'),('D', 'E'),('E', 'G')] # Set of edges

for e in E:
	print(e)

# Construct the adjacency matrix
N = len(V)
adj = np.zeros((N, N))     # zeros initialise kelay adjacncy matrix madhe

for e in E:
	for k, v in enumerate(V):         # v = ('S', 7)
		if e[0] == v[0]:          # v[0] = S, v[1] = 7
			index1 = k
			# print("Here 1 = ",e[0], v1, v[1], v[0], k)
	for k, v in enumerate(V):
		if e[1] == v[0]:
			index2 = k
			# print(e[1], v[2], v[0], k)
	adj[index1, index2] = 1

print("Adj matrix = "+str(adj))

# Array to mark whether or not a node is visited. mark = mark as visited
mark = np.zeros((N))
parentNode = [-1]* N

# For finding start and finish from the V list
# start = V.index('S')
# finish = V.index('G')
# Mark the start node and the goal node
for k, v in enumerate(V):
	if v[0] == 'S':
		start = k
	if v[0] == 'G':
		finish = k


nodesUnexplored = [start]
# # heuristics
def gettheHeuristicValue(node):
	return V[node][1]

while nodesUnexplored:
	currentNode = min(nodesUnexplored, key=gettheHeuristicValue)   # get the element from the unexpl list that gives smallest valu when passed to the function. current node as node with min heuristic value
	nodesUnexplored.remove(currentNode)														# remove that node bcz now we have visited it
	mark[currentNode] = 1
	print(currentNode)

  # Reached the goal
	if currentNode == finish:
		print("Goal node"+str(currentNode)+" found.")
		break

	for nextNode in range(N):
		# if the new node is adjacent to current node and not yet marked as visited and it is not in nodesUnexplored
		if adj[currentNode, nextNode] == 1 and mark[nextNode] == 0 and nextNode not in nodesUnexplored:
			parentNode[nextNode] = currentNode
			nodesUnexplored.append(nextNode)

	print(parentNode)

if parentNode[finish] == -1:
	print("There is no path from S to G")
else:
	path = []
	v = finish
	while v != -1:
		path.append(v)
		v = parentNode[v]
	path.reverse()
	name_path = [V[x][0] for x in path]
	print("Path from S to G:")
print(name_path)


('S', 'A')
('S', 'D')
('A', 'B')
('A', 'C')
('B', 'C')
('B', 'E')
('C', 'G')
('D', 'B')
('D', 'E')
('E', 'G')
Adj matrix = [[0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]]
0
[-1, 0, -1, -1, 0, -1, -1]
4
[-1, 0, 4, -1, 0, 4, -1]
5
[-1, 0, 4, -1, 0, 4, 5]
6
Goal node6 found.
Path from S to G:
['S', 'D', 'E', 'G']


Problem 2 (A* Tree Search)

In [35]:
import numpy as np
import heapq

# Graph
V = [('S', 7), ('A', 9), ('B', 4), ('C', 2), ('D', 5), ('E', 3), ('G', 0)]
E = [('S', 'A', 3), ('S', 'D', 2), ('A', 'B', 5), ('A', 'C', 10), ('B', 'C', 2),
     ('B', 'E', 1), ('C', 'G', 4), ('D', 'B', 1), ('D', 'E', 4), ('E', 'G', 3)]

# Build adjacency matrix
N = len(V)
adjmat = np.zeros((N, N))
for e in E:
    for k, node in enumerate(V):
        if e[0] == node[0]:
            index1 = k
        if e[1] == node[0]:
            index2 = k
    adjmat[index1, index2] = e[2]   # edge cost

# Start and Goal
for i, node in enumerate(V):
    if node[0] == 'S':
        start = i
    if node[0] == 'G':
        finish = i

# A* Tree Search
Datatuplesheap = []
path = [start]
g = 0
f = g + V[start][1]

# Push the initial f, g and path value path = start node
heapq.heappush(Datatuplesheap, (f, g, path))

while Datatuplesheap:
    # Push f, g, path to heap
    f, gVal, path = heapq.heappop(Datatuplesheap)
    # if path = S->D->B then current node = B so path[-1]
    currentNode = path[-1]

    if currentNode == finish:
        print("Found the goal node. ")
        print(" -> ".join(V[x][0] for x in path))
        print("Cost obtained finally is this = " + str(gVal))
        break

    for nextNode in range(N):
        if adjmat[currentNode, nextNode] > 0:
            g1 = gVal + adjmat[currentNode, nextNode]
            f1 = g1 + V[nextNode][1]
            path1 = path + [nextNode]
            heapq.heappush(Datatuplesheap, (f1, g1, path1))


Found the goal node. 
S -> D -> B -> E -> G
Cost obtained finally is this = 7.0


A* Graph Search


In [ ]:
import numpy as np
import heapq

# Graph
V = [('S', 7), ('A', 9), ('B', 4), ('C', 2), ('D', 5), ('E', 3), ('G', 0)]
E = [('S', 'A', 3), ('S', 'D', 2), ('A', 'B', 5), ('A', 'C', 10), ('B', 'C', 2),
     ('B', 'E', 1), ('C', 'G', 4), ('D', 'B', 1), ('D', 'E', 4), ('E', 'G', 3)]

# adjacency matrix adj
N = len(V)
adj = np.zeros((N, N))
large = 10e9
for e in E:
    for k, node in enumerate(V):
        if e[0] == node[0]:
            index1 = k
        if e[1] == node[0]:
            index2 = k
    adj[index1, index2] = e[2]           # assigned cost
print("Adjacency Matrix \n")
print(adj)

# START and GOAL node init
for i, node in enumerate(V):
    if node[0] == 'S':
        start = i
    if node[0] == 'G':
        finish = i

# A* Tree Search
Datatuplesheap = []
path = [start]
g = 0
f = g + V[start][1]
g_valueTracker = {start: 0}

heapq.heappush(Datatuplesheap, (f, g, path))

while Datatuplesheap:
    f, gVal, path = heapq.heappop(Datatuplesheap)
    currentNode = path[-1]

    if gVal > g_valueTracker.get(currentNode, float(large)):
        continue

    if currentNode == finish:
      print("Found the goal node. ")
      for x in path:
        print(" -> ".join(V[x][0]))
      print("Cost obtained finally is this = "+str(gVal))
      break

    for nextNode in range(N):
        if adj[currentNode, nextNode] > 0:
            g1 = gVal + adj[currentNode, nextNode]

            # if better path to the goal node s available using lesser g value then we switch
            if g1 < g_valueTracker.get(nextNode, float(large)):
                g_valueTracker[nextNode] = g1
                f1 = g1 + V[nextNode][1]
                path1 = path + [nextNode]
                heapq.heappush(Datatuplesheap, (f1, g1, path1))

Adjacency Matrix 

[[ 0.  3.  0.  0.  2.  0.  0.]
 [ 0.  0.  5. 10.  0.  0.  0.]
 [ 0.  0.  0.  2.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  4.]
 [ 0.  0.  1.  0.  0.  4.  0.]
 [ 0.  0.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
Found the goal node. 
S
D
B
E
G
Cost obtained finally is this = 7.0


4. Knights Tour Problem

In [ ]:
import numpy as np
from operator import itemgetter

# 1. User Input
N = int(input("Enter size: "))
startRow = int(input("Enter start row: "))
startCol = int(input("Enter start column: "))
chessboard = np.full((N, N), -1)

def possibleMoves(x, y, chessboard):
    moves = [(1, -2), (2, -1), (2, 1), (1, 2), (-1, 2), (-2, 1), (-2, -1), (-1, -2)]

    correctknightmoves = []

    for move_x, move_y in moves:
        newmoveX = x + move_x
        newmoveY = y + move_y

        # check if the move is inside the board and not visited
        if 0 <= newmoveX < N and 0 <= newmoveY < N and chessboard[newmoveX][newmoveY] == -1:

            # count valid next moves using heuristic Warnsdroff algo
            degreeOfMove = 0
            for (movex, movey) in moves:
                newx, newy = newmoveX + movex, newmoveY + movey
                if 0 <= newx < N and 0 <= newy < N :
                  if chessboard[newx][newy] == -1:
                    degreeOfMove += 1

            correctknightmoves.append((newmoveX, newmoveY, degreeOfMove))

    # sort based on degree = Warnsdorff's algo
    sortedknightmoves = sorted(correctknightmoves, key=itemgetter(2))

    # coordinate values returned
    return [(xcoord, ycoord) for xcoord, ycoord, degree in sortedknightmoves]

def Chessboard_KnightTour(row, col, moveNum, chessboard):
    # Mark current position
    chessboard[row][col] = moveNum

    # If all squares are visited, STOP it
    if moveNum == N * N:
        return True

    # Get all possible next moves
    Moves = possibleMoves(row, col, chessboard)

    # Try each possible move
    for next_x, next_y in Moves:
        if Chessboard_KnightTour(next_x, next_y, moveNum + 1, chessboard):
            return True

    # BACKTRACK: If move is wrong go back to prev step
    chessboard[row][col] = -1
    return False

def display(chessboard):
    print(f"** Knight's Tour **")
    print(f"Starting position: ({startRow}, {startCol})")

    for row in range(N):
        for col in range(N):
            print(f"{chessboard[row][col]:3d}", end=" ")
        print()
    print()

# Convert to 0-based indexing for processing
start_x = startRow - 1
start_y = startCol - 1

# Solve the Knight's Tour
if Chessboard_KnightTour(start_x, start_y, 1, chessboard):
    display(chessboard)
else:
    print("No solution")

Enter size: 8
Enter start row: 1
Enter start column: 1
** Knight's Tour **
Starting position: (1, 1)
  1  26  15  24  29  36  13  32 
 16  23  28  35  14  31  40  37 
 27   2  25  30  61  38  33  12 
 22  17  62  45  34  41  50  39 
  3  46  21  60  49  64  11  42 
 18  57  48  63  44  53   8  51 
 47   4  55  20  59   6  43  10 
 56  19  58   5  54   9  52   7 



**Problem 5. Intelligent Agent**

In [2]:
# Input data from submarine.in and lets print
import heapq

costDict = {}
inf = 10e9

def readInptfromFile():
    # it will be submarineLarge.in for larg check
    with open("submarine.in", "r") as inputFile:
        inputData = inputFile.read().strip().splitlines()
        # print(inputData)
    T = int(inputData[0])      # T = testcase
    index = 1
    testcaseData = []
    print("testcase Total =", T)

    for test in range(T):   # runing for ecach testcase
        # first line of any testcase = rows and cols
        numrows, numcols = map(int, inputData[index].split())
        index += 1

        # according to the rows and cols = we declare grid
        Boundry = []
        for rw in range(numrows):
            # get elements of grid
            rowValues = inputData[index].split()
            index += 1
            Boundry.append(rowValues)
        # the whole testcses stored in thes format
        testcaseData.append((numrows, numcols, Boundry))
        # print(testcaseData)
    return testcaseData

def checkForStartanGoalNode(Boundry, numrows, numCols):
    strt = None
    goal =  None
    for row in range(numrows):
        for col in range(numCols):
            if Boundry[row][col] == 'S':
                # if node = strt node then store its row and col in start
                strt = (row, col)
            if Boundry[row][col] == 'G':
                # goal node = store (row, col) = goal
                goal = (row, col)

    # if no strt and no goal there in our input it is error. Nothing to do here
    if strt == None or goal == None:
        return None, None
    return strt, goal

def InitCostsForNodesAll(Boundry, start, goal, numrows, numcols, posibleMovement):
    costDict.clear()
    # cost of start = 0
    costDict[(start[0], start[1], None)] = 0
    return costDict

def checkIfMoveValid(row, col, boundry, numrows, numcols):
    if row < 0 or row >= numrows or col < 0 or col >= numcols:
        return "Invalid"
    else:
        if boundry[row][col] == '0' or boundry[row][col] == 0:
            return "Invalid"
    return "Valid"

def implementingDikshtras(Boundry, start, goal, numrows, numcols, posibleMovement, costDict, priorityQueue):

    # if start = goal then i dont think there are any other nodes within them we reach the goal that is endpoint
    if start == goal:
        return 0

    # if not, just traverse thrugh all nodes in priorityQueue
    while priorityQueue:
        # everytime we pop we get 4 element. cost, row, col of the element, till now direction that
        # we traversed to reach the current node
        costFromQueue, row, col, lastdirection = heapq.heappop(priorityQueue)

        # we reach goal so return
        if (row, col) == goal:
            return costFromQueue

        # we have one more dict to handle cost - handlecost - costfr costdict.
        # in that storing row, col and last what was the direction we choose because we should not travel same direction two times like that it is invalid
        #  dont do this and initialise and put inf as the distance for all nodes first only
        # first check if a particular row, col is not in costDict then return inf otherwise cost.
        costFromCostDict = costDict.get((row, col, lastdirection), inf)

        # if cost from queue is greater then dont update the costDict -> because we want minimal cost always
        if costFromQueue > costFromCostDict:
            continue

        for rowInc, colInc, currentdir in posibleMovement:
            # Cannot move in the same direction again and again
            if currentdir == lastdirection:
                continue

            # add new row and col from posibleMovement for going to new position from current position
            # posibleMOvement has [-1, 0] then row -1 and col + 0 . This will take us to new position
            newRow = row + rowInc
            newCol = col + colInc

            # after getting new position (row, col). It shoudl still be inside the boundry
            if newRow < 0 or newRow >= numrows or newCol < 0 or newCol >= numcols:
                continue

            # now should Check for iland
            if Boundry[newRow][newCol] == '0' or Boundry[newRow][newCol] == 0:
                continue

            # should Calculate cel cost
            cell_value = Boundry[newRow][newCol]
            if cell_value in ('S', 'G'):
                # strt and goal will have = 0 cost
                costOfGridCell = 0
            else:
                # get cost from our input grid now cheh
                costOfGridCell = int(cell_value)

            # should add this grid cost with queue cost
            final_cost = costFromQueue + costOfGridCell
            currentCostFromCostDict = costDict.get((newRow, newCol, currentdir), inf)

            if final_cost < currentCostFromCostDict:
                costDict[(newRow, newCol, currentdir)] = final_cost
                heapq.heappush(priorityQueue, (final_cost, newRow, newCol, currentdir))

    return -1


testcaseData = readInptfromFile()
reslts = []

for numrows, numcols, Boundry in testcaseData:
    strt, goal = checkForStartanGoalNode(Boundry, numrows, numcols)
    # if we dont have strt or goal we retun -1 as the final ans
    if strt is None or goal is None:
        reslts.append(-1)
        continue

    # from any position we can move nort, south, est, west. Thisis initial we are declaring
    # anytime we want to go norht you add current position with row = -1 and col = 0 like that we can go north
    posibleMovement = [(-1, 0, 'N'), (1, 0, 'S'), (0, -1, 'W'), (0, 1, 'E')]
    costDict = InitCostsForNodesAll(Boundry, strt, goal, numrows, numcols, posibleMovement)

    # our priorityque = cost, row, col, path.
    #
    priorityQueue = [(0, strt[0], strt[1], None)]
    # print(priorityQueue)

    result = implementingDikshtras(Boundry, strt, goal, numrows, numcols, posibleMovement, costDict, priorityQueue)
    reslts.append(result)

# Write output to file
with open("submarine.out", "w") as outptFile:
    for result in reslts:
        outptFile.write(str(result) + "\n")

print("submarine.out:", reslts)

testcase Total = 10
submarine.out: [-1, -1, 13, 21, 34, 6, 6, 32, 5, 6]
